SELECT
       TD.IDTURMADISC              AS ID_TURMADISC,
       TD.CODTURMA                 AS COD_TURMA,
       T.NOME                      AS NOME_TURMA,
       TD.CODFILIAL                AS CODFILIAL,
       TD.CODDISC                  AS CODDISC,
       D.NOME                      AS NOME_DISCIPLINA,
       D.NOMEREDUZIDO              AS NOME_DISC_REDUZIDO,
       TD.ATIVA                    AS TURMADISC_ATIVA,
       TC.NOME                     AS NIVEL_ENSINO,
       HF.CODCURSO                 AS CODCURSO,
       HF.DESCRICAOCURSO           AS NOME_CURSO,
       PR.CODPROF                  AS CODPROF,
       PR.CHAPA                    AS CHAPA,
       PP.NOME                     AS NOME_PROFESSOR,
       PP.EMAIL                    AS EMAIL_PROFESSOR,
       PP.EMAILPESSOAL             AS EMAIL_PROF_PESSOAL,
       PT.STATUS                   AS STATUS_PROF_TURMA,
       PL.CODPERLET                AS CODPERLET,
       PL.DESCRICAO                AS PERIODO_LETIVO
FROM   STURMADISC TD
JOIN   SPLETIVO PL ON PL.CODCOLIGADA = TD.CODCOLIGADA
                  AND PL.IDPERLET    = TD.IDPERLET
JOIN   STURMA   T  ON T.CODCOLIGADA  = TD.CODCOLIGADA
                  AND T.CODFILIAL    = TD.CODFILIAL
                  AND T.CODTURMA     = TD.CODTURMA
                  AND T.IDPERLET     = TD.IDPERLET
LEFT JOIN SDISCIPLINA D ON D.CODCOLIGADA = TD.CODCOLIGADA
                       AND D.CODDISC     = TD.CODDISC
LEFT JOIN STIPOCURSO TC ON TC.CODCOLIGADA  = T.CODCOLIGADA
                       AND TC.CODTIPOCURSO = T.CODTIPOCURSO
LEFT JOIN SHABILITACAOFILIAL HF ON HF.CODCOLIGADA = T.CODCOLIGADA
                               AND HF.IDHABILITACAOFILIAL = T.IDHABILITACAOFILIAL
LEFT JOIN SPROFESSORTURMA PT ON PT.CODCOLIGADA = TD.CODCOLIGADA
                            AND PT.IDTURMADISC = TD.IDTURMADISC
LEFT JOIN SPROFESSOR PR ON PR.CODCOLIGADA = PT.CODCOLIGADA
                       AND PR.CODPROF     = PT.CODPROF
LEFT JOIN PPESSOA PP ON PP.CODIGO = PR.CODPESSOA
WHERE  TD.CODCOLIGADA = :CODCOLIGADA
  AND  PL.CODPERLET   = :CODPERLET
ORDER BY T.NOME, D.NOME, PP.NOME
