SELECT A.RA                              AS RA,
       PA.NOME                           AS ALUNO,

       A.CODPESSOARACA                   AS COD_RESP_ACADEMICO,
       PR.NOME                           AS RESP_ACADEMICO,
       PR.EMAIL                          AS EMAIL_ACADEMICO,
       PR.EMAILPESSOAL                   AS EMAIL_ACAD_PESSOAL,
       PKA.DESCRICAO                     AS PARENTESCO_ACADEMICO,

       A.CODCOLCFO                       AS COLIGADA_CFO,
       A.CODCFO                          AS COD_RESP_FINANCEIRO,
       CF.NOME                           AS RESP_FINANCEIRO,
       CF.EMAIL                          AS EMAIL_FINANCEIRO,
       PKF.DESCRICAO                     AS PARENTESCO_FINANCEIRO

FROM   SALUNO A
JOIN   PPESSOA PA ON PA.CODIGO = A.CODPESSOA
JOIN   SMATRICPL M ON M.CODCOLIGADA = A.CODCOLIGADA
                  AND M.RA          = A.RA
JOIN   SPLETIVO PL ON PL.CODCOLIGADA = M.CODCOLIGADA
                  AND PL.IDPERLET    = M.IDPERLET
LEFT JOIN PPESSOA PR ON PR.CODIGO = A.CODPESSOARACA
LEFT JOIN PCODPARENT PKA ON PKA.CODCLIENTE = A.CODPARENTRACA
LEFT JOIN FCFO CF ON CF.CODCOLIGADA = A.CODCOLCFO
                 AND CF.CODCFO      = A.CODCFO
LEFT JOIN PCODPARENT PKF ON PKF.CODCLIENTE = A.CODPARENTCFO
WHERE  A.CODCOLIGADA = :CODCOLIGADA
  AND  PL.CODPERLET  = :CODPERLET
GROUP BY A.RA, PA.NOME,
         A.CODPESSOARACA, PR.NOME, PR.EMAIL, PR.EMAILPESSOAL, PKA.DESCRICAO,
         A.CODCOLCFO, A.CODCFO, CF.NOME, CF.EMAIL, PKF.DESCRICAO
ORDER BY A.RA;
