SELECT F.CODCOLIGADA                  AS CODCOLIGADA,
       F.RA                           AS RA,
       F.IDTURMADISC                  AS ID_TURMADISC,
       F.DATA                         AS DATA,
       F.IDHORARIOTURMA               AS ID_HORARIO_TURMA,

       F.PRESENCA                     AS PRESENCA,

       F.JUSTIFICADA                  AS JUSTIFICADA,
       F.IDJUSTIFICATIVAFALTA         AS ID_JUSTIFICATIVA,
       J.DESCRICAO                    AS JUSTIFICATIVA_DESCRICAO,
       J.COMPOETOTALFALTAS            AS COMPOE_TOTAL_FALTAS,

       HT.CODHOR                      AS CODHOR,
       HT.CODHORARIOTURMA             AS CODHORARIOTURMA,
       SUBSTRING(CAST(HT.CODHOR AS VARCHAR(30)), 5, 3)  AS FAIXA_DE_CODHOR,
       H.AULA                         AS NUMERO_AULA,
       H.DIASEMANA                    AS DIASEMANA,
       H.HORAINICIAL                  AS HORAINICIAL,
       H.HORAFINAL                    AS HORAFINAL,
       H.CODTURNO                     AS CODTURNO,

       TD.CODTURMA                    AS COD_TURMA,
       TD.CODDISC                     AS CODDISC,
       TD.CODFILIAL                   AS CODFILIAL,
       PL.CODPERLET                   AS CODPERLET,

       F.RECCREATEDBY                 AS CRIADO_POR,
       F.RECCREATEDON                 AS CRIADO_EM,
       F.RECMODIFIEDBY                AS ALTERADO_POR,
       F.RECMODIFIEDON                AS ALTERADO_EM

FROM   SFREQUENCIA F
JOIN   STURMADISC TD ON TD.CODCOLIGADA  = F.CODCOLIGADA
                    AND TD.IDTURMADISC  = F.IDTURMADISC
JOIN   SPLETIVO PL ON PL.CODCOLIGADA = TD.CODCOLIGADA
                  AND PL.IDPERLET    = TD.IDPERLET
LEFT JOIN SHORARIOTURMA HT ON HT.CODCOLIGADA    = F.CODCOLIGADA
                          AND HT.IDHORARIOTURMA = F.IDHORARIOTURMA
LEFT JOIN SJUSTIFICATIVAFALTA J ON J.CODCOLIGADA          = F.CODCOLIGADA
                               AND J.IDJUSTIFICATIVAFALTA = F.IDJUSTIFICATIVAFALTA

OUTER APPLY (
       SELECT TOP 1 S.DIASEMANA, S.HORAINICIAL, S.HORAFINAL, S.AULA, S.CODTURNO
       FROM   SHORARIO S
       WHERE  S.CODCOLIGADA = HT.CODCOLIGADA
         AND  S.CODHOR      = HT.CODHOR
       ORDER BY CASE WHEN S.IDPERLET = TD.IDPERLET THEN 0 ELSE 1 END, S.AULA
) H
WHERE  F.CODCOLIGADA = :CODCOLIGADA
  AND  PL.CODPERLET  = :CODPERLET
  AND  F.DATA       >= CONVERT(DATE, CAST(:DATAINICIAL AS VARCHAR(8)), 112)
  AND  F.DATA        < DATEADD(DAY, 1, CONVERT(DATE, CAST(:DATAFINAL AS VARCHAR(8)), 112))
ORDER BY F.DATA, TD.CODTURMA, TD.CODDISC, F.RA;
