SELECT
    NE.CODCOLIGADA                AS CODCOLIGADA,
    NE.RA                         AS RA,
    NE.IDTURMADISC                AS ID_TURMADISC,
    NE.CODETAPA                   AS CODETAPA,
    NE.TIPOETAPA                  AS TIPOETAPA,
    E.DESCRICAO                   AS ETAPA,
    NE.NOTAFALTA                  AS NOTA,
    NE.CODCONCEITO                AS COD_CONCEITO,
    NE.IDGRUPO                    AS ID_GRUPO_CONCEITO,
    CO.NOTAINI                    AS CONCEITO_NOTA_INI,
    CO.NOTAFIM                    AS CONCEITO_NOTA_FIM,
    NE.AULASDADAS                 AS AULAS_DADAS,
    TD.CODFILIAL                  AS CODFILIAL,
    TD.CODTURMA                   AS COD_TURMA,
    TD.CODDISC                    AS CODDISC,
    D.NOME                        AS DISCIPLINA,
    M.CODSTATUS                   AS STATUS,
    ST.DESCRICAO                  AS STATUS_DESCRICAO,
    ST.PLATIVO                    AS STATUS_ATIVO,
    E.DTINICIO                    AS ETAPA_DT_INICIO,
    E.DTFIM                       AS ETAPA_DT_FIM,
    E.DISPONIVELALUNOS            AS ETAPA_LIBERADA,
    PL.CODPERLET                  AS CODPERLET,
    NE.RECCREATEDBY               AS CRIADO_POR,
    NE.RECCREATEDON               AS CRIADO_EM,
    NE.RECMODIFIEDBY              AS ALTERADO_POR,
    NE.RECMODIFIEDON              AS ALTERADO_EM
FROM   SNOTAETAPA NE
           JOIN   STURMADISC TD ON TD.CODCOLIGADA = NE.CODCOLIGADA
    AND TD.IDTURMADISC = NE.IDTURMADISC
           JOIN   SPLETIVO PL ON PL.CODCOLIGADA = TD.CODCOLIGADA
    AND PL.IDPERLET    = TD.IDPERLET
           JOIN   SETAPAS E ON E.CODCOLIGADA = NE.CODCOLIGADA
    AND E.IDTURMADISC = NE.IDTURMADISC
    AND E.CODETAPA    = NE.CODETAPA
    AND E.TIPOETAPA   = NE.TIPOETAPA
           LEFT JOIN SDISCIPLINA D ON D.CODCOLIGADA = TD.CODCOLIGADA
    AND D.CODDISC     = TD.CODDISC
           LEFT JOIN SMATRICULA M ON M.CODCOLIGADA = NE.CODCOLIGADA
    AND M.IDTURMADISC = NE.IDTURMADISC
    AND M.RA          = NE.RA
           LEFT JOIN SCONCEITO CO ON CO.CODCOLIGADA = NE.CODCOLIGADA
    AND CO.IDGRUPO     = NE.IDGRUPO
    AND CO.CODCONCEITO = NE.CODCONCEITO
    OUTER APPLY (
       SELECT TOP 1 S.DESCRICAO, S.PLATIVO
       FROM   SSTATUS S
       WHERE  S.CODCOLIGADA = M.CODCOLIGADA
         AND  S.CODSTATUS   = M.CODSTATUS
       ORDER BY S.CODTIPOCURSO
) ST
WHERE  NE.CODCOLIGADA = :CODCOLIGADA
  AND  PL.CODPERLET   = :CODPERLET
  AND  NE.TIPOETAPA   = 'N'
ORDER BY TD.CODTURMA, TD.CODDISC, NE.CODETAPA, NE.RA
