SELECT

       TD.IDTURMADISC                 AS ID_TURMADISC,
       TD.CODTURMA                    AS COD_TURMA,
       T.NOME                         AS NOME_TURMA,
       TD.CODFILIAL                   AS CODFILIAL,

       SUBSTRING(TD.CODTURMA, 4, 2)   AS SEGMENTO,
       SUBSTRING(TD.CODTURMA, 6, 2)   AS SERIE,
       SUBSTRING(TD.CODTURMA, 8, 1)   AS TURNO,
       SUBSTRING(TD.CODTURMA, 9, 1)   AS SECAO,

       TD.CODDISC                     AS CODDISC,
       D.NOME                         AS NOME_DISCIPLINA,

       PR.CODPROF                     AS CODPROF,
       PP.NOME                        AS NOME_PROFESSOR,

       PP.EMAIL                       AS EMAIL_PROFESSOR,
       PP.EMAILPESSOAL                AS EMAIL_PROF_PESSOAL,
       PT.AULASSEMANAISPROF           AS AULAS_SEMANAIS,

       TD.ATIVA                       AS TURMADISC_ATIVA,
       PT.STATUS                      AS STATUS_PROF_TURMA,

       PL.CODPERLET                   AS CODPERLET,
       PL.DESCRICAO                   AS PERIODO_LETIVO
FROM   STURMADISC TD
JOIN   SPLETIVO PL ON PL.CODCOLIGADA = TD.CODCOLIGADA
                  AND PL.IDPERLET    = TD.IDPERLET
JOIN   STURMA   T  ON T.CODCOLIGADA  = TD.CODCOLIGADA
                  AND T.CODFILIAL    = TD.CODFILIAL
                  AND T.CODTURMA     = TD.CODTURMA
                  AND T.IDPERLET     = TD.IDPERLET
LEFT JOIN SDISCIPLINA D ON D.CODCOLIGADA = TD.CODCOLIGADA
                       AND D.CODDISC     = TD.CODDISC

LEFT JOIN SPROFESSORTURMA PT ON PT.CODCOLIGADA = TD.CODCOLIGADA
                            AND PT.IDTURMADISC = TD.IDTURMADISC
LEFT JOIN SPROFESSOR PR ON PR.CODCOLIGADA = PT.CODCOLIGADA
                       AND PR.CODPROF     = PT.CODPROF
LEFT JOIN PPESSOA PP ON PP.CODIGO = PR.CODPESSOA
WHERE  TD.CODCOLIGADA = :CODCOLIGADA
  AND  PL.CODPERLET   = :CODPERLET

ORDER BY TD.CODTURMA, TD.CODDISC, PR.CODPROF;
