SELECT PA.CODCOLIGADA                 AS CODCOLIGADA,
       PA.IDTURMADISC                 AS ID_TURMADISC,
       PA.IDPLANOAULA                 AS ID_PLANOAULA,
       PA.IDHORARIOTURMA              AS ID_HORARIO_TURMA,
       PA.AULA                        AS NUMERO_AULA,

       PA.DATA                        AS DATA,
       PA.DATAEFETIVA                 AS DATA_EFETIVA,
       PA.REPOSICAO                   AS REPOSICAO,

       PA.CONTEUDO                    AS CONTEUDO_PREVISTO,
       PA.CONTEUDOEFETIVO             AS CONTEUDO_MINISTRADO,
       PA.LICAOCASA                   AS LICAO_CASA,
       PA.OBSERVACAO                  AS OBSERVACAO,

       PA.CONFIRMADO                  AS CONFIRMADO,
       PA.TIPOAULA                    AS TIPO_AULA,
       PA.FREQUENCIADISPWEB           AS FREQ_DISP_WEB,

       TD.CODTURMA                    AS COD_TURMA,
       TD.CODDISC                     AS CODDISC,
       D.NOME                         AS NOME_DISCIPLINA,
       PA.CODFILIAL                   AS CODFILIAL,
       TD.ATIVA                       AS TURMADISC_ATIVA,

       PA.CODPROF                     AS CODPROF,
       PP.NOME                        AS NOME_PROFESSOR,
       PA.SUBSTITUTO                  AS SUBSTITUTO,

       H.DIASEMANA                    AS DIASEMANA,
       H.HORAINICIAL                  AS HORAINICIAL,
       H.HORAFINAL                    AS HORAFINAL,

       PA.RECCREATEDBY                AS CRIADO_POR,
       PA.RECCREATEDON                AS CRIADO_EM,
       PA.RECMODIFIEDBY               AS ALTERADO_POR,
       PA.RECMODIFIEDON               AS ALTERADO_EM,

       PL.CODPERLET                   AS CODPERLET,
       PL.DESCRICAO                   AS PERIODO_LETIVO

FROM   SPLANOAULA PA
JOIN   STURMADISC TD ON TD.CODCOLIGADA = PA.CODCOLIGADA
                    AND TD.IDTURMADISC = PA.IDTURMADISC
JOIN   SPLETIVO PL ON PL.CODCOLIGADA = TD.CODCOLIGADA
                  AND PL.IDPERLET    = TD.IDPERLET
LEFT JOIN SDISCIPLINA D ON D.CODCOLIGADA = TD.CODCOLIGADA
                       AND D.CODDISC     = TD.CODDISC
LEFT JOIN SPROFESSOR PR ON PR.CODCOLIGADA = PA.CODCOLIGADA
                       AND PR.CODPROF     = PA.CODPROF
LEFT JOIN PPESSOA PP ON PP.CODIGO = PR.CODPESSOA

OUTER APPLY (
       SELECT TOP 1 S.DIASEMANA, S.HORAINICIAL, S.HORAFINAL
       FROM   SHORARIO S
       WHERE  S.CODCOLIGADA = PA.CODCOLIGADA
         AND  S.CODHOR      = PA.CODHOR
       ORDER BY CASE WHEN S.IDPERLET = TD.IDPERLET THEN 0 ELSE 1 END, S.AULA
) H

WHERE  PA.CODCOLIGADA = :CODCOLIGADA
  AND  PL.CODPERLET   = :CODPERLET
  AND  PA.DATA       >= CONVERT(DATE, CAST(:DATAINICIAL AS VARCHAR(8)), 112)
  AND  PA.DATA        < DATEADD(DAY, 1, CONVERT(DATE, CAST(:DATAFINAL AS VARCHAR(8)), 112))
ORDER BY PA.DATA, TD.CODTURMA, TD.CODDISC, PA.AULA;
